### ISSUE TITLE
Error:(168, 0) Cause: repository not found

### ISSUE THREAD

**Issue by unNene** [ushahidi/platform-android#1]
Hi,

I'm using Android Studio 1.1.0 and after I imported the application I tried to compile it. I can't because I see this error:

Error:(168, 0) Cause: repository not found: <my home directory>../platform-android-master

On line 168 of file build.gradle I can see: grgit = Grgit.open(dir: '.')

How can I fix this problem ?

**Comment by eyedol** [comment]
@unNene It should be a git repo as we use that for versioning. Clone the repo
