### ISSUE TITLE
What program did you use to create this application?

### ISSUE THREAD

**Issue by unstephenk** [ushahidi/platform-android#5]
I am interested. Everything seems pretty well organized just in strange places. Please let me know, it will make this much easier..

**Comment by eyedol** [comment]
No program. Wrote it from scratch. It's based on the clean architecture. Of course with couple of ideas and works from others. If you're interested in reading more about the clean architecture, read this [post](https://blog.8thlight.com/uncle-bob/2011/11/22/Clean-Architecture.html). Feel free to ask for specifics why things are where they're. I'm happy to help.
