### ISSUE TITLE
Get Deployment Info From API

### ISSUE THREAD

**Issue by eyedol** [ushahidi/platform-android#67]
Using the endpoint, instead of asking the user to enter title and description, get those details via the API; api/v3/config/site

**Comment by eyedol** [comment]
@pramodcs Could you look into this? Essentially want to get the deployment title and description from the API. http://whereintheworldis-ushahidi-api.herokuapp.com/api/v3/config/site.

You enter the API URL, hit save, make a request to the `api/v3/config/site` endpoint, then get the `title` and `description` fields and save them in the database.

This means you have to remove the fields for manually entering the `title` and the `description`

Let me know if you need further info.

**Comment by pramodcs** [comment]
I don't see a field for entering description. In fact, I don't see any place where description is being set or used.

Is there anything I am missing?

**Comment by eyedol** [comment]
@pramodcs  You're right. The description field has been discarded. It seems, I removed it as some point since we weren't visualizing it anywhere. Feel free to discard it.
