### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by pramodcs** [ushahidi/platform-android#72]
Sometimes logout button shows up even when a user is not logged in. This is because the instruction "mSessionManager.getActiveSession() != null" evaluates to true in PostActivity. i.e., There is an active session when no user is logged in. 

We should have a better way of detecting whether user is logged in or not.

**Comment by eyedol** [comment]
@pramodcs mind taking a look at this?

**Comment by eyedol** [comment]
@pramodcs how is this coming along?
