### ISSUE TITLE
Categories button is inactive. Unable to create reports

### ISSUE THREAD

**Issue by copystar** [ushahidi/platform-android#76]
Hello. I created a web instance of a map (bikerackswindsor) and then downloaded the Android Ushahidi app from the play store. I was able to successfully import my empty map into Android. I then went outside to create a report. It would not let me because I did not select a category. I returned to my web instance and created two categories. Still, I could not create a report outside because the categories button is inactive and not reflecting that there should be two categories to choose from. Please let me know if you need further information.

**Comment by eyedol** [comment]
@copystar The Android app from the Playstore is not compatible with the current version 3.x.x of the platform. If you were using it with version 2.x.x of the platform, then possibly you've discovered a bug.

Which Ushahidi version are you using the Android app from the Playstore against?

**Comment by copystar** [comment]
Apologies for my late response. Yes, I was working with v.3.9. Will wait until the update happens. Everything else looks great! Thank you!
